# Generated by Django 3.2.7 on 2022-06-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resposta', '0001_initial'),
        ('pergunta', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.IntegerField()),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('empresa_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresamaster')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.empresaquestionario')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pergunta.pergunta')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resposta.resposta')),
            ],
        ),
    ]
