# Generated by Django 3.2.7 on 2022-06-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(blank=True, max_length=45)),
                ('bairro', models.CharField(blank=True, max_length=45)),
                ('cidade', models.CharField(blank=True, max_length=45)),
                ('complemento', models.CharField(blank=True, max_length=45)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uf.uf')),
            ],
        ),
    ]
