# Generated by Django 3.2.7 on 2022-06-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fundamento', '0001_initial'),
        ('resposta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(max_length=5000)),
                ('conceito', models.CharField(blank=True, max_length=5000)),
                ('objetivo', models.CharField(blank=True, max_length=5000)),
                ('fundamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fundamento.fundamento')),
                ('respostas', models.ManyToManyField(to='resposta.Resposta')),
            ],
        ),
    ]
