# Generated by Django 3.2.7 on 2022-06-26 21:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('questionario', '0001_initial'),
        ('tipo_diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.consultor')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionario.questionario')),
                ('tipo_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_diagnostico.tipodiagnostico')),
            ],
        ),
    ]
